name: CI
on:
  push:
    branches: [ main, 16-unittest ] # Adjust branches as needed
  pull_request:
    branches: [ main, 16-unittest ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Restore dependencies
      run: dotnet restore MainAPISolution/MainAPISolution.sln
    - name: Build
      run: dotnet build MainAPISolution/MainAPISolution.sln --no-restore --configuration Release
    - name: Test with Coverage
      run: dotnet test MainAPISolution/MainAPISolution.sln --no-build --configuration Release --verbosity detailed /p:CollectCoverage=true /p:CoverletOutputFormat=opencover